# Menyuruh Railway mengaktifkan 2 bahasa sekaligus (Resmi)
providers =["node", "python"]

# Tahap Build untuk React/Vite
[phases.build]
cmds = ["npm run build"]

# Tahap menjalankan kedua mesin bersamaan
[start]
cmd = "node bridge.js & python guardian_bot.py"
