[variables]
# Mematikan proteksi virtual environment Python agar instalasi pip tidak diblokir
PIP_BREAK_SYSTEM_PACKAGES = "1"

[phases.setup]
# Memaksa mesin mengunduh Node 20 (berisi npm), Python 3, dan paket Pip secara bersamaan
nixPkgs =["nodejs_20", "python3", "python3Packages.pip", "gcc"]

[phases.install]
cmds =[
  "npm install",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
][start]
cmd = "node bridge.js & python3 guardian_bot.py"
